---
title: "movie rating"
author: "GAN LING"
date: "2017/4/12"
output: html_document
---

#### load data

```{r}
# before doing this, you need to use python to run the edit_users_movies_dat.py
# file to clean the dat data
# deal with users_clean.dat
users = read.csv("users_clean.dat", sep = "=", header = FALSE, col.names = c("UserID","Gender","Age","Occupation","Zip-code"))
# deal with movies_utf8_clean.dat
movie = read.csv("movies_utf8_clean.dat", sep = "=", header = FALSE, col.names = c("MovieID","Title","Genres"))
# deal with training_ratings_for_kaggle_comp.csv
# training_ratings = read.csv("training_ratings_for_kaggle_comp.csv")
# save(training_ratings, file = "training_ratings.RData")
load("training_ratings.RData")
```

#### combine the data, because this needs time, we can save the result for next time, this part we use one and half an hour to deal with the data and get 116858 observasion.

```{r}
# combine_user = function (users, training_ratings, stopnum){
#     k = 1
#     for (d in training_ratings$user){
#         if (d > stopnum){
#             break
#         }
#         temp_row = data.frame(users[users$UserID == d, c(2,3,4)])
#         print(temp_row)
#         if (k == 1){
#             temp_get = temp_row
#             k = 0
#         }
#         else{
#             temp_get = rbind(temp_get, temp_row)
#         }
#     }
#     cbind(training_ratings[1:nrow(temp_get),], temp_get)
# }
# # get all of the data out when the rating equal to 5. Because we only care about the data with the highest evaluation.
# newraitings = combine_user(users, training_ratings[training_ratings$rating==5,], 6040)
# save(newraitings, file = "newraitings1.RData")

#load the data we save to save time
load("newraitings1.RData")
```